update semantic release package
patrickhulce/git3po pull request #31
Opened 2021-12-16 23:12 UTC by paulirish

fixes #30 

following https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/ci-configurations/github-actions.md

but not using NPX..

2021-12-16 23:29 UTC, patrickhulce requested changes

2021-12-16 23:29 UTC, patrickhulce commented on .github/workflows/ci.yml
> +      run: npm run semantic-release
For this to match the docs need to update package.json to just run `semantic-release` right (currently its that old `pre && publish && post` method?

2021-12-16 23:36 UTC, paulirish commented on .github/workflows/ci.yml
> +      run: npm run semantic-release
good catch. didnt spot that.

2021-12-17 01:06 UTC, patrickhulce approved these changes

2021-12-17 01:06 UTC, merged

2021-12-17 01:06 UTC, patrickhulce commented
3rd time's a charm :)